# Generated by Django 4.2.2 on 2023-06-24 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='fltipo',
            field=models.IntegerField(choices=[(0, 'Produto'), (1, 'Serviço')], default=0, verbose_name='Tipo'),
            preserve_default=False,
        ),
    ]
