# Generated by Django 4.2.2 on 2023-06-24 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_produto_fltipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='condicaopagamento',
            name='dtexclusao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='dtexclusao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='empresaendereco',
            name='dtexclusao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='estoque',
            name='dtexclusao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='formapagamento',
            name='dtexclusao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='dtexclusao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pessoadocumento',
            name='dtexclusao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pessoaendereco',
            name='dtexclusao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='produto',
            name='dtexclusao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='secao',
            name='dtexclusao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tipodocumento',
            name='dtexclusao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='unidade',
            name='dtexclusao',
            field=models.DateField(blank=True, null=True),
        ),
    ]
