# Generated by Django 4.2.2 on 2023-06-24 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_idempresa_empresaendereco_empresa_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estoquemovimento',
            old_name='nrquantidade',
            new_name='quantidade',
        ),
        migrations.RenameField(
            model_name='estoquemovimento',
            old_name='nrsqldo',
            new_name='saldo',
        ),
        migrations.AlterField(
            model_name='configuracao',
            name='dschaveapi',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Chave da API'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='dsinscricaoestadual',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Inscrição estadual'),
        ),
        migrations.AlterField(
            model_name='empresaendereco',
            name='dsUF',
            field=models.CharField(blank=True, choices=[('RO', 'Rondônia'), ('AC', 'Acre'), ('AM', 'Amazonas'), ('RR', 'Roraima'), ('PA', 'Pará'), ('AP', 'Amapá'), ('TO', 'Tocantins'), ('MA', 'Maranhão'), ('PI', 'Piauí'), ('CE', 'Ceará'), ('RN', 'Rio Grande do Norte'), ('PB', 'Paraíba'), ('PE', 'Pernambuco'), ('AL', 'Alagoas'), ('SE', 'Sergipe'), ('BA', 'Bahia'), ('MG', 'Minas Gerais'), ('ES', 'Espírito Santo'), ('RJ', 'Rio de Janeiro'), ('SP', 'São Paulo'), ('PR', 'Paraná'), ('SC', 'Santa Catarina'), ('RS', 'Rio Grande do Sul'), ('MS', 'Mato Grosso do Sul'), ('MT', 'Mato Grosso'), ('GO', 'Goiás'), ('DF', 'Distrito Federal')], max_length=2, null=True, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='empresaendereco',
            name='dsbairro',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Endereço'),
        ),
        migrations.AlterField(
            model_name='empresaendereco',
            name='dscep',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='Cep'),
        ),
        migrations.AlterField(
            model_name='empresaendereco',
            name='dscidade',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Endereço'),
        ),
        migrations.AlterField(
            model_name='ordemservico',
            name='dtpromessa',
            field=models.DateField(blank=True, null=True, verbose_name='Prometido para'),
        ),
        migrations.AlterField(
            model_name='ordemservico',
            name='valorlimite',
            field=models.FloatField(blank=True, null=True, verbose_name='Fazer até no valor de'),
        ),
        migrations.AlterField(
            model_name='ordemservicoequipamento',
            name='dsmarca',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Marca'),
        ),
        migrations.AlterField(
            model_name='ordemservicoequipamento',
            name='nrserie',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Número de série'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='dtnascimento',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Nascimento'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='pessoaendereco',
            name='dsbairro',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='pessoaendereco',
            name='dscelular',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='pessoaendereco',
            name='dscep',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='pessoaendereco',
            name='dscidade',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Cidade'),
        ),
        migrations.AlterField(
            model_name='pessoaendereco',
            name='dstelefone',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='cdreferencia',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Código de referência'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='nrcodigobarras',
            field=models.CharField(blank=True, max_length=18, null=True, verbose_name='Código de barras'),
        ),
    ]
