# Generated by Django 4.2.2 on 2023-06-24 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_nrquantidade_estoquemovimento_quantidade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='vlmargem',
            field=models.FloatField(blank=True, null=True, verbose_name='Margem de lucro'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='vlprecocusto',
            field=models.FloatField(blank=True, null=True, verbose_name='Preço de custo'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='vlprecovenda',
            field=models.FloatField(blank=True, null=True, verbose_name='Preço de venda'),
        ),
    ]
